In [36]:
from backtesting import Backtest, Strategy
from backtesting.test import GOOG
import numpy as np
import pandas_ta as ta

GOOG["signal"] = np.random.randint(-1,2,len(GOOG))

def indicator(data):
    #data is going to be our OHLCV
    bbands = ta.bbands(close = data.Close.s, std=1)
    print (bbands.to_numpy())
    return bbands.to_numpy()


class BBStrategy(Strategy):
    
    def init(self):
        self.bbands = self.I(indicator,self.data)   
        print(self.bbands)
    
    def next(self):
        lower_band = self.bbands[0]
        upper_band = self.bbands[2]
        
        if self.position:
            if self.data.Close[-1] > upper_band[-1]:
                self.position.close()
        else:
            if self.data.Close[-1] < lower_band[-1]:
                self.buy()
    

bt = Backtest(GOOG, BBStrategy, cash=10000)

output = bt.run()
bt.plot()

[[         nan          nan          nan          nan          nan]
 [         nan          nan          nan          nan          nan]
 [         nan          nan          nan          nan          nan]
 ...
 [791.01857277 795.184      799.34942723   1.04766374   1.05168411]
 [791.49313358 796.318      801.14286642   1.21179389   1.00592074]
 [791.38584907 797.614      803.84215093   1.56169549   1.18848685]]
[[         nan          nan          nan ... 791.01857277 791.49313358
  791.38584907]
 [         nan          nan          nan ... 795.184      796.318
  797.614     ]
 [         nan          nan          nan ... 799.34942723 801.14286642
  803.84215093]
 [         nan          nan          nan ...   1.04766374   1.21179389
    1.56169549]
 [         nan          nan          nan ...   1.05168411   1.00592074
    1.18848685]]


Row(id='10082', ...)

In [33]:
output

Start                     2004-08-19 00:00:00
End                       2013-03-01 00:00:00
Duration                   3116 days 00:00:00
Exposure Time [%]                         0.0
Equity Final [$]                      10000.0
Equity Peak [$]                       10000.0
Return [%]                                0.0
Buy & Hold Return [%]              703.458242
Return (Ann.) [%]                         0.0
Volatility (Ann.) [%]                     0.0
Sharpe Ratio                              NaN
Sortino Ratio                             NaN
Calmar Ratio                              NaN
Max. Drawdown [%]                        -0.0
Avg. Drawdown [%]                         NaN
Max. Drawdown Duration                    NaN
Avg. Drawdown Duration                    NaN
# Trades                                    0
Win Rate [%]                              NaN
Best Trade [%]                            NaN
Worst Trade [%]                           NaN
Avg. Trade [%]                    

In [26]:
!pip install pandas_ta

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.1/115.1 kB 1.6 MB/s eta 0:00:00 MB/s eta 0:00:01
  Preparing metadata (setup.py) ... done
  Created wheel for pandas_ta: filename=pandas_ta-0.3.14b0-py3-none-any.whl size=218907 sha256=784f07fce521b52870d72038ea0e1b92fbe5b600923ff143965ab2d11c63cf01
  Stored in directory: /Users/johnsonhsiao/Library/Caches/pip/wheels/1e/5c/47/759b32beb377aee150eb4c1f1b2b7635032cc19ea09ce076fd
Successfully built pandas_ta
